### ISSUE TITLE
Theme preview action is not working anymore.

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1899]
**Describe the bug**
It looks like the theme preview action is not working anymore (see https://github.com/anuraghazra/github-readme-stats/runs/7561423249?check_suite_focus=true). It gives the following warning message:

```log
Error: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 1,2 >>> },  github: {     t ...
    at error (/home/runner/work/github-readme-stats/github-readme-stats/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/home/runner/work/github-readme-stats/github-readme-stats/node_modules/hjson/lib/hjson-parse.js:163:9)
    at object (/home/runner/work/github-readme-stats/github-readme-stats/node_modules/hjson/lib/hjson-parse.js:353:[15](https://github.com/anuraghazra/github-readme-stats/runs/7561423249?check_suite_focus=true#step:4:16))
    at legacyRootValue (/home/runner/work/github-readme-stats/github-readme-stats/node_modules/hjson/lib/hjson-parse.js:434:28)
    at Object.module.exports [as parse] (/home/runner/work/github-readme-stats/github-readme-stats/node_modules/hjson/lib/hjson-parse.js:454:23)
    at run (/home/runner/work/github-readme-stats/github-readme-stats/scripts/preview-theme.js:115:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  hint: ''
```

Probably a simple parsing error caused by how `git diff displays the new changes. Not a high priority, but putting it here so that we don't forget.

**Comment by steven-steven** [comment]
Hi, a new contributor here. I've made a PR that should fix this issue. Appreciate any reviews :)

**Comment by rickstaa** [comment]
@steven-steven First of all, welcome to the community 😄 and thanks for creating this valuable PR. 🚀
