### ISSUE TITLE
Error: Node.js version 12.x has reached End-of-Life

### ISSUE THREAD

**Issue by navilg** [anuraghazra/github-readme-stats#1900]
**Describe the bug**

Vercel is throwing the error during build.

```
Running "vercel build"
Vercel CLI 27.3.0
Error: Node.js version 12.x has reached End-of-Life. Deployments created on or after 2022-08-09 will fail to build. Please set Node.js Version to 16.x in your Project Settings to use Node.js 16.
```

**Expected behaviour**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by rickstaa** [comment]
@navilg Thanks a lot for letting us know! I fixed this in #1901. Please check out the updated master branch.

**Comment by inovramadani** [comment]
I got the same error:
```
Error: Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.
```

I tried adding in package.json:
```
  "engines": {
    "node": "18.x"
  }
```

But it brings another error:
```
> next build
--
10:04:31.655 |  
10:04:32.299 | Browserslist: caniuse-lite is outdated. Please run next command `npm update`
10:04:32.382 | Creating an optimized production build...
10:04:32.425 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
10:04:32.425 | This information is used to shape Next.js' roadmap and prioritize features.
10:04:32.426 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
10:04:32.426 | https://nextjs.org/telemetry
10:04:32.426 |  
10:04:32.707 | Error: error:0308010C:digital envelope routines::unsupported
10:04:32.707 | at new Hash (node:internal/crypto/hash:71:19)
10:04:32.707 | at Object.createHash (node:crypto:133:10)
10:04:32.707 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
10:04:32.707 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:412:16)
10:04:32.707 | at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:463:10)
10:04:32.708 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:495:5
10:04:32.708 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:354:12
10:04:32.708 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
10:04:32.708 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
10:04:32.708 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
10:04:32.710 | Error: error:0308010C:digital envelope routines::unsupported
10:04:32.710 | at Object.createHash (node:crypto:133:10)
10:04:32.710 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
10:04:32.710 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:412:16)
10:04:32.710 | at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:463:10)
10:04:32.711 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:495:5
10:04:32.711 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:354:12
10:04:32.711 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
10:04:32.711 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
10:04:32.711 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
10:04:32.712 | Error: error:0308010C:digital envelope routines::unsupported
10:04:32.713 | at new Hash (node:internal/crypto/hash:71:19)
10:04:32.713 | at Object.createHash (node:crypto:133:10)
10:04:32.713 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
10:04:32.713 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:412:16)
10:04:32.713 | at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:463:10)
10:04:32.713 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:495:5
10:04:32.713 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:354:12
10:04:32.713 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
10:04:32.713 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
10:04:32.713 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
10:04:32.810 | node:internal/crypto/hash:71
10:04:32.810 | this[kHandle] = new _Hash(algorithm, xofLen);
10:04:32.810 | ^
10:04:32.810 |  
10:04:32.810 | Error: error:0308010C:digital envelope routines::unsupported
10:04:32.810 | at new Hash (node:internal/crypto/hash:71:19)
10:04:32.811 | at Object.createHash (node:crypto:133:10)
10:04:32.811 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
10:04:32.811 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:412:16)
10:04:32.811 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:444:10
10:04:32.811 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:320:13
10:04:32.811 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
10:04:32.811 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
10:04:32.812 | at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
10:04:32.812 | at /vercel/path0/node_modules/babel-loader/lib/index.js:55:103 {
10:04:32.812 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
10:04:32.812 | library: 'digital envelope routines',
10:04:32.812 | reason: 'unsupported',
10:04:32.812 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
10:04:32.812 | }
10:04:32.812 |  
10:04:32.813 | Node.js v18.12.1
10:04:32.840 | Error: Command "npm run build" exited with 1
```

How to fix?

**Comment by inovramadani** [comment]
I found the solution, apparently updating should be done from the vercel settings instead: https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version
